# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target ‘bookmark’ do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bookmark
  pod 'FlatUIKit', :git => 'https://github.com/lpniuniu/FlatUIKit', :branch => 'master'
  pod 'SnapKit'
  pod 'Bulb', :git => 'https://github.com/lpniuniu/bulb', :branch => 'master'
  pod 'BlocksKit'
  pod 'SCLAlertView', :git => 'https://github.com/lpniuniu/SCLAlertView-Swift.git', :branch => 'master'
  pod 'SWTableViewCell', :git => 'https://github.com/lpniuniu/SWTableViewCell', :branch => 'master'
  pod 'RealmSwift'
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'Toast-Swift'
  pod 'JTAppleCalendar'
  pod 'BTNavigationDropdownMenu', :git => 'https://github.com/PhamBaTho/BTNavigationDropdownMenu.git', :branch => 'swift-3.0'
  pod 'Eureka', '~> 2.0.0-beta.1'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Charts'
  target 'bookmarkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
