# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bookmark' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bookmark
  pod 'RAMAnimatedTabBarController', "~> 2.0.13" # swift 3  
  pod 'FlatUIKit', :git => 'https://github.com/lpniuniu/FlatUIKit', :branch => 'master'
  pod 'SnapKit', '~> 3.0.2'
  pod 'Bulb', :git => 'https://github.com/lpniuniu/bulb.git', :branch => 'master'
  target 'bookmarkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
