# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bookmark' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bookmark
  pod 'FlatUIKit', :git => 'https://github.com/lpniuniu/FlatUIKit', :branch => 'master'
  pod 'SnapKit'
  pod 'Bulb', :git => 'https://github.com/lpniuniu/bulb', :branch => 'master'
  pod 'BlocksKit'
  target 'bookmarkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
